endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    workspaces-api:
      path: /workspaces-service/**
    employees-api:
      path: /employees-service/**

